"""update column

Revision ID: 0e2831fd23c4
Revises: 8e8be2db559b
Create Date: 2026-06-11 16:26:51.919048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2831fd23c4'
down_revision: Union[str, Sequence[str], None] = '8e8be2db559b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('summary', sa.String(length=120), nullable=True))
    op.drop_column('comments', 'sumary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('sumary', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('comments', 'summary')
    # ### end Alembic commands ###
