"""fixed models

Revision ID: 47b045cbc24a
Revises: 0e2831fd23c4
Create Date: 2026-06-15 16:27:12.769432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b045cbc24a'
down_revision: Union[str, Sequence[str], None] = '0e2831fd23c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saveds', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'saveds', 'authors', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('saveds', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saveds', sa.Column('user', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saveds', type_='foreignkey')
    op.drop_column('saveds', 'user_id')
    # ### end Alembic commands ###
