"""add created_at column

Revision ID: 8e8be2db559b
Revises: e4d35adbe9e9
Create Date: 2026-06-11 16:17:51.803395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8be2db559b'
down_revision: Union[str, Sequence[str], None] = 'e4d35adbe9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('saveds', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saveds', 'created_at')
    op.drop_column('comments', 'created_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('books', 'created_at')
    op.drop_column('authors', 'created_at')
    # ### end Alembic commands ###
